entrada/urls.py
from django.urls import path
from .views import list_entrada, new_entrada, update_entrada, delete_entrada
app_name = 'entrada'
urlpatterns = [
    path('list_entrada/', list_entrada, name='list_entrada'),
    path('new_entrada/', new_entrada, name='new_entrada'),
    path('update_entrada/<int:pk>/', update_entrada, name='update_entrada'),
    path('delete_entrada/<int:pk>/', delete_entrada, name='delete_entrada'),
]

estoque/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('', index, name='index'),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida')),
    path('admin/', admin.site.urls),
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto,delete_produto
app_name = 'produto'
urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto, name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name='delete_produto'),
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida
app_name = 'saida'
urlpatterns = [
    path('list_saida/', list_saida, name='list_saida'),
    path('new_saida/', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida, name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name='delete_saida'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def index(request):
    template_name = 'index.html'
    context = {
        'mensagem': 'Bem vindo à aplicação estoqueWeb'
    }
    return render(request, template_name, context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br" data-theme="light">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Django</title>
<link rel="stylesheet" href="{% static 'css/bulma.css' %}">
</head>
<body>
  <div class="container">
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
        <div class="navbar-brand" style="margin-left: 5px;">      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="{% url 'produto:list_produto' %}">Produtos</a>
            <a class="navbar-item" href="{% url 'entrada:list_entrada' %}">Entradas</a>
            <a class="navbar-item" href="{% url 'saida:list_saida' %}">Saída</a>
          </div>
        </div>
    </nav>
    <br>

    {% comment %} <div class="notification is-primary">
      This container is <strong>centered</strong> on desktop and larger viewports.
    </div> {% endcomment %}

      {% block product %}{% endblock %}
  </div>
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% block product %}
<h1>Aplicação estoqueWeb</h1>
<p>Praesent sapien massa, convallis a pellentesque nec,
egestas non nisi. Praesent sapien massa, convallis a
pellentesque nec, egestas non nisi. Sed porttitor lectus nibh.
Vivamus magna justo, lacinia eget consectetur sed, convallis
at tellus. Proin eget to rtor risus. Vivamus suscipit tortor
eget felis porttitor volutpat. Nulla porttitor accumsan
tincidunt. Nulla porttitor accumsan tincidunt. Vestibulum ante
ipsum primis in faucibus orci luctus et ultrices posuere
cubilia Curae; Donec velit neque, auctor sit ametaliquam vel,
ullamcorper sit amet ligula. Praesent sapien massa, convallis
a pellentesque nec, egestas non nisi.</p>
{% endblock %}